---
- name: Configure Database Play
  hosts: db
  gather_facts: yes
  become: true

  vars:
    web_ip: '192.168.33.10'
    db_ip: '192.168.33.11'
    db_port: '3306'
    mysql_db_name: 'ecomdb'
    mysql_user: 'ecomuser'
    mysql_user_password: "{{ mysql_password }}"  # Stored in vault

  tasks:
  - name: Ensure MariaDB is installed
    apt:
      name: mariadb-server
      state: present

  - name: Ensure MariaDB is started and enabled
    service:
      name: mariadb
      state: started
      enabled: yes

  - name: Ensure firewall is configured for database
    firewalld:
      port: "{{ db_port }}/tcp"
      zone: public
      permanent: yes
      state: enabled

  - name: Reload service firewalld
    systemd:
      name: firewalld
      state: reloaded

  - name: Ensure PyMySQL is installed
    apt:
      name: python3-pymysql
      state: present

  - name: Update config file
    lineinfile:
      path: /etc/mysql/mariadb.conf.d/50-server.cnf
      regexp: "{{ item.regexp_find }}"
      line: "{{ item.to_replace }}"
    with_items:
      - { regexp_find: '^#port', to_replace: "port = {{ db_port }}"}
      - { regexp_find: '^bind-address', to_replace: "bind-address = {{ db_ip }}"}

  - name: Start mysql
    service:
      name: mysql
      state: started
      enabled: yes

  - name: Add user account "ecomuser" for localhost
    mysql_user:
      check_implicit_admin: true
      login_unix_socket: /var/run/mysqld/mysqld.sock # For passwordless signin - https://stackoverflow.com/questions/63791797/why-can-ansible-not-connect-to-mysql
      name: "{{ mysql_user }}"
      host: 'localhost'
      password: "{{ mysql_user_password }}"
      priv: "*.*:ALL,GRANT"
      state: present
    loop:
      - 'localhost'
      - "{{ web_ip }}"

  - name: Ensure no database with name "{{ mysql_db_name }}"
    mysql_db:
      login_user: "{{ mysql_user }}"
      login_password: "{{ mysql_user_password }}"
      name: "{{ mysql_db_name }}"
      state: absent

  - name: Add /tmp/db-load-script.sql
    file:
      path: /tmp/db-load-script.sql
      state: touch
      mode: '0644'

  # same setup as demo-repo
  - name: Ensure the db-load-script.sql is present
    blockinfile:
      path: /tmp/db-load-script.sql
      block: |
        USE '{{ mysql_db_name }}';
        CREATE TABLE products (id mediumint(8) unsigned NOT NULL auto_increment,Name varchar(255) default NULL,Price varchar(255) default NULL, ImageUrl varchar(255) default NULL,PRIMARY KEY (id)) AUTO_INCREMENT=1;

        INSERT INTO products (Name,Price,ImageUrl) VALUES ("Laptop","100","c-1.png"),("Drone","200","c-2.png"),("VR","300","c-3.png"),("Tablet","50","c-5.png"),("Watch","90","c-6.png"),("Phone Covers","20","c-7.png"),("Phone","80","c-8.png"),("Laptop","150","c-4.png");

  - name: Create database name "{{ mysql_db_name }}"
    mysql_db:
      login_user: "{{ mysql_user }}"
      login_password: "{{ mysql_user_password }}"
      name: "{{ mysql_db_name }}"
      state: present

  - name: Seed database
    mysql_db:
      login_user: "{{ mysql_user }}"
      login_password: "{{ mysql_user_password }}"
      state: import
      name: "{{ mysql_db_name }}"
      target: /tmp/db-load-script.sql