---
- name: Pre-Requisites
  hosts: all
  gather_facts: yes
  become: true

  tasks:
  - name: Ensure firewalld is installed
    apt:
      name: firewalld
      state: present

  - name: Ensure firewalld is started
    service:
      name: firewalld
      state: started
      enabled: yes