---
- name: Configure Web node
  hosts: web
  become: true
  gather_facts: yes

  vars:
    web_ip: '192.168.33.10'
    db_ip: '192.168.33.11'
    web_port: '80'
    mysql_db_name: 'ecomdb'
    mysql_user: 'ecomuser'
    mysql_user_password: "{{ mysql_password }}"

  tasks:
  - name: Check present packages
    apt:
      name: 
        - apache2
        - php
        - php-mysql
      state: present

  - name: Ensure firewall is configured for apache2
    firewalld:
      port: "{{ web_port }}/tcp"
      zone: public
      permanent: yes
      state: enabled

  - name: Reload service firewalld
    service:
      name: firewalld
      state: reloaded
    
  - name: Update DirectoryIndex
    lineinfile:
      path: /etc/apache2/mods-enabled/dir.conf
      search_string: 'DirectoryIndex'
      line: "\tDirectoryIndex index.php index.html index.cgi index.pl index.xhtml index.htm"

  - name: Start & enable apache2
    service:
      name: apache2
      state: started
      enabled: yes

  - name: Empty /var/www/html/ for our Repo
    file:
      state: absent
      path: /var/www/html/

  - name: clone Repo
    git:
      repo: 'https://github.com/kodekloudhub/learning-app-ecommerce.git'
      dest: /var/www/html/

  - name: Update index.php to connect to database
    lineinfile:
      path: /var/www/html/index.php
      search_string: "$link = mysqli_connect"
      line: "$link = mysqli_connect('{{ db_ip }}', '{{ mysql_user }}', '{{ mysql_user_password }}', '{{ mysql_db_name }}');"