---
- hosts: web
  gather_facts: yes
  become: true

  tasks:
    - name: update & upgrade
      apt:
        upgrade: yes
        update_cache: yes
        
    - name: Install nginx
      apt: pkg=nginx state=present

    - name: delete default nginx conf
      file:
        state: absent
        path: /etc/nginx/sites-available/default

    - name: Touch a file, using symbolic modes to set the permissions (equ$
      file:
        path: /etc/nginx/sites-available/default
        state: touch
        mode: '666'

    - name: Insert multiple lines and Backup
      blockinfile:
        path: /etc/nginx/sites-available/default
        backup: yes
        block: |
          ##

          server {
                  listen 80 default_server;
                  listen [::]:80 default_server;

                  root /var/www/html;

                  index index.html index.htm index.nginx-debian.html;

                  server_name _;

                  location / {
                  try_files $uri $uri/ =404;
                  proxy_pass http://localhost:3000/;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection "upgrade";
                  proxy_set_header Host $http_host;
                  proxy_cache_bypass $http_upgrade;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Scheme $scheme;
                  }

                  location /fibonacci/ {
                  proxy_pass http://localhost:3000/fibonacci/;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade \$http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host \$host;
                  proxy_cache_bypass \$http_upgrade;
                  }
          }


