---
- name: Configure Database
  hosts: web  # to be changed
  gather_facts: yes
  become: true

  tasks:
  - name: Ensure MariaDB is installed
    apt:
      name: mariadb-server
      state: present
      update_cache: yes

  - name: Ensure MariaDB is started and enabled
    service:
      name: mariadb
      state: started
      enabled: yes

  - name: Ensure firewall is configured for database
    firewalld:
      port: 3306/tcp
      zone: public
      permanent: yes
      state: enabled

  - name: Reload service firewalld
    systemd:
      name: firewalld
      state: reloaded

  - name: Create a new database with name 'ecomdb'
    community.mysql.mysql_db:
      name: ecomdb
      state: present