Vagrant.configure("2") do |config|

    config.vm.define "web" do |web|
        config.vm.box = "bento/ubuntu-20.04"
        web.vm.hostname = "web"
        web.vm.network "private_network", ip: "192.168.33.10"
        web.vm.provision "shell", path: "vagrant-provision/web-provisioning.sh"
    end 

    config.vm.define "controller" do |controller|
        config.vm.box = "bento/ubuntu-20.04"
        controller.vm.hostname = "controller"
        controller.vm.network "private_network", ip: "192.168.33.12"
        controller.vm.provision "shell", path: "vagrant-provision/controller-provisioning.sh"
        controller.vm.provision "file", source: "ansible-playbooks/", destination: "~/"
    end

end