---
- name: Pre-Requisites
  hosts: web
  gather_facts: yes
  become: true

  tasks:
  - name: Ensure firewalld is installed
    apt:
      name: firewalld
      state: present
      update_cache: yes

  - name: Ensure firewalld is started
    service:
      name: firewalld
      state: started
      enabled: yes