---
- hosts: db
  become: true
  tasks:
    - name: install mongodb
      apt:
        name: mongodb
        state: present
        update_cache: yes
    - name: start and enable mongod
      shell: |
        sudo sed -i 's/bind_ip = 1.0.0.0/bind_ip = 0.0.0.0/' /etc/mongodb.conf
        sudo systemctl start mongod
        sudo systemctl enable mongod