---
# where do we want to install nginx
- hosts: awsdb

# do we want to see logs - gather facts
  gather_facts: yes

# what permissions do we need to run this playbook, become sudo
  become: true
  # used for sudo/admin access

# what is the name of the package, -name is case-insensitive
  tasks:
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Upgrade all apt packages
    apt: upgrade=dist force_apt_get=yes

  - name: install Python
    apt: pkg=python3 state=present

  - name: copy app folder
    copy: src=/home/vagrant/eng110-cicd-main dest=.

  - name: copy db-provision file
    copy: src=/home/vagrant/db_provision.sh dest=.

  - name: run db_provision.sh
    shell: |
      chmod +x db_provision.sh
      bash db_provision.sh
